#!/usr/bin/env python3

import re
import subprocess
import yaml


def installed_roles() -> dict[str, str]:
    '''Get the installed Ansible roles via `ansible-galaxy list` and return a
    dictionary of playbooks and their versions..
    '''
    result = subprocess.run(['ansible-galaxy', 'list'], stdout=subprocess.PIPE)
    roles = yaml.safe_load(result.stdout)
    result = {}
    for role in roles:
        name, version = role.split(',', 1)
        result[name] = version.strip()
    return result


def main():
    # Get required and installed roles
    with open('requirements.yml', 'r') as f:
        requirements = yaml.safe_load(f)
    installed = installed_roles()

    for role in requirements.get('roles', []):
        name = role.get('name')
        if not name:
            if role.get('scm') == 'git' and role.get('src'):
                name = re.search('/([^/]*)\\.git', role['src']).group(1)
            else:
                print(f'WARNING: could not handle {role}')
        if not name:
            continue
        if name not in installed:
            print(f'ERROR: role {name} is not installed')
            exit(1)
        version = role.get('version')
        if version and installed[name] != version:
            print(f'ERROR: role {name} has incorrect version')
            print(f'  required: {version}')
            print(f'  present: {installed[name]}')
            exit(1)


if __name__ == '__main__':
    main()
